import "./index.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { AuthProvider } from "@/components/providers/auth-provider";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "400 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Triad Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} bg-zinc-950`}>
      <body className="antialiased">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
