import "@triad/ui/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Triad Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">{children}</body>
    </html>
  );
}
